/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://xxxxxxxxx.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-west-2:xxxxxxxxxxx-xxxxx-xxxx-xxx-xxxxxxxxxxx",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_xxxxxxxxxx",
    "aws_user_pools_web_client_id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
    "oauth": {},
    "aws_user_files_s3_bucket": "xxxxxxx-storage-bucketxxxxxxxx-production",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
